language: php

php:
  - 5.4

before_script:
  - wget --quiet http://getcomposer.org/composer.phar
  - php composer.phar install
  - cp phpunit.xml.dist phpunit.xml

script: sudo phpunit --coverage-text