language: php

php:
  - 5.4

before_script:
  # PHP Unit (with database)
  - export ORIANCCI_PHPUNIT_HOSTTYPE="mysql"
  - export ORIANCCI_PHPUNIT_HOSTNAME="127.0.0.1"
  - export ORIANCCI_PHPUNIT_USERNAME="root"
  - export ORIANCCI_PHPUNIT_PASSWORD=
  - export ORIANCCI_PHPUNIT_DATABASE="oriancci_build"

  # Database
  - mysql -e 'CREATE DATABASE oriancci_build;'
  - mysql oriancci_build < tests/Oriancci/fixtures/schema.sql

  # Composer
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: bin/phpunit -c phpunit.xml.dist