language: php

php:
  - 5.4

before_script:
  # PHP Unit (with database)
  - pear config-set auto_discover 1
  - pear install phpunit/DbUnit

  # Database
  - mysql -e 'CREATE DATABASE oriancci_build;'

  # Composer
  - composer install

env: ORIANCCI_PHPUNIT_HOSTTYPE=mysql ORIANCCI_PHPUNIT_HOSTNAME=127.0.0.1 ORIANCCI_PHPUNIT_USERNAME=root ORIANCCI_PHPUNIT_PASSWORD= ORIANCCI_PHPUNIT_DATABASE=oriancci_build

script: phpunit tests/