language: php

php:
  - 5.4

before_script:
  # PHP Unit (with database)
  - pear config-set auto_discover 1
  - pear install pear.phpunit.de/PHPUnit
  - pear install phpunit/DbUnit
  - export ORIANCCI_PHPUNIT_HOSTTYPE="mysql"
  - export ORIANCCI_PHPUNIT_HOSTNAME="127.0.0.1"
  - export ORIANCCI_PHPUNIT_USERNAME="root"
  - export ORIANCCI_PHPUNIT_PASSWORD=
  - export ORIANCCI_PHPUNIT_DATABASE="oriancci_build"

  # Database
  - mysql -e 'CREATE DATABASE oriancci_build;'

  # Composer
  - composer install

script: phpunit -c phpunit.xml.dist tests/